name: mensaje3-app

services:
  - name: web
    github:
      repo: SebastianWebApp/Practica-Grupal-P4-Mensaje3
      branch: desarrollo
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    # Puerto que expone tu app en Express
    http_port: 3000

    # Variables de entorno si usas dotenv o algo similar
    envs:
      - key: NODE_ENV
        value: production
      # Agrega aquí otras variables que uses, por ejemplo:
      # - key: DB_HOST
      #   value: tu_host
      # - key: DB_USER
      #   value: tu_usuario
      # - key: DB_PASS
      #   value: tu_password
